### ISSUE TITLE
Feature: Hierarchical Navigation View (Dev Tracking)

### ISSUE THREAD

**Issue by ojhad** [microsoft/microsoft-ui-xaml#1317]
Tracking work for #79 
(List & structure may change a bit in the coming days)

- [x] **Wait for the task [Update NavigationView to use ItemsRepeater] (https://github.com/microsoft/microsoft-ui-xaml/issues/1477) to be completed**

**Update control to allow for hierarchical selection**
- [x] Update selection to be able to handle leveled selection
  - [x] Correctly handle user interaction selection routes Left Navigation View
  - [x] Correctly handle API selection routes Left Navigation View
  - [x] Correctly handle user interaction selection routes Top Navigation View
  - [x] Correctly handle API selection routes Top Navigation View
- [x] Update usage of IndexPath within NavigationView to expect more than one level
- [x] Write some tests to verify these selection scenarios

**Create NavigationViewItem API and Test App Code**
- [x] Update IDL files and corresponding classes
- [x] Create TestApp Pages
- [x] Write some basic initial tests

**Hierarchical Navigation View For Left Expanded Mode**
- [x] Update NVI to be able to display nested repeater and menu items
- [x] add Expanding/Collapsing behavior
- [x] proper selection indicator display (isChildSelected) markup
- [x] proper selection indicator display (isChildSelected) databinding

**Heirarchical Navigation View for Left Compact Mode**
- [x] Update NVI to be able to display its menu items in a flyout to the right 
  - [x] write logic to allow for the back and forth movement of items between main list and flyout
- [x] Update selection to work between main list and flyout
- [x] Update visuals (selection indicator, etc.) to work between main list and flyout

**Hierarchical Navigation View for Top and Top Overflow modes**
- [x] Update Top NVI to be able to display its menu items in a flyout below
- [x] Update 'More' flyout to work with the overflow flyout
- [x] Verify selection behavior
- [x] Animation

**Flyout Behaviors**
- [x] Update flyout (overflow and normal) behavior to be consistent when selection is changed (for example in scenarios where an item with children vs leaf node is selected)

**Accessibility and Narrator Support**
- [x] Update NVI Automation Peer (look at scroll to item)
- [ ] Write AP specific tests
- [ ] Verify Narrator support
- [ ] Verify keyboarding support

**Add Animations to match motion comps**
- [x] Add selection indicator animations
- [x] Add chevron and chevron animations

**Create NavigationViewItem Template Settings**
- [ ] Create NavigationViewItem Template Settings
