### ISSUE TITLE
Update NavigationView to use ItemsRepeater (Dev Tracking)

### ISSUE THREAD

**Issue by ojhad** [microsoft/microsoft-ui-xaml#1477]
Tracking work for https://github.com/microsoft/microsoft-ui-xaml/issues/378

**Review Test Coverage**
- [x] Verify visual tree verification test coverage is expansive (1 day)
- [x]  Verify that test coverage is expansive enough to catch potential problems during the move (0.5 day)

**Update Selection Logic To Use SelectionModel**
- [x] Integrate SelectionModel to handle single level selection
  - [x] Update NavigationViewItemBase & NavigationViewItem to be responsible for selection (2 days)
    - [x]  NVI and NVIB Regular selection logic
    - [x] Account for Settings item selection
    - [x] For TopNav, account for keeping track of selection state between Primary and Overflow menu
  - [x] Hook up current NavigationView selection related APIs to SelectionModel (SelectedItem, SelecitonChanged event, etc) (1 day)

**Move to Repeater**
- [x] Write custom implementation of IElementFactory to handle wrapping of content in NVI items (0.5 day)
- [x] Update NVI to be responsible for handling interaction events (1 day)
  - [x] SelectionFollowsFocus behavior
- [x] Implement functionality to handle MenuItemContainerStyle/MenuItemContainerStyleSelector API (0.5 day)
- [x] Move LeftNav to Repeater (1 day)
  - [x] Have Repeater for in MarkUp and Databinding scenarios
- [x] Move TopNav to Repeater (2 day)
  - [x] Have Repeater for in MarkUp and Databinding scenarios
  - [x] Hook up SplitDataSource implementation to Repeater implementation
  - [x] Simplify existing width sizing logic in MeasureOverride
- [x] Update Animations (if needed) (1 day)

**AutomationPeer**
- [x] NavigationViewItemAutomationPeer/NavigationViewAutomationPeer (1 day)

**Revisit issues/PRs that are dependent on this refactor**
  - [x] https://github.com/microsoft/microsoft-ui-xaml/pull/1497#event-2747596359
  - [x] https://github.com/microsoft/microsoft-ui-xaml/pull/1395
  - [x] https://github.com/microsoft/microsoft-ui-xaml/issues/1572

**Comment by ad1Dima** [comment]
FYI: Updated #1497 based on your PR 
https://github.com/ad1Dima/microsoft-ui-xaml/tree/user/ad1Dima/NavigationView_BottomMenuItems_repeaterbased

**Comment by ojhad** [comment]
> FYI: Updated #1497 based on your PR
> https://github.com/ad1Dima/microsoft-ui-xaml/tree/user/ad1Dima/NavigationView_BottomMenuItems_repeaterbased

@ad1Dima I am going to close this issue as the refactor is now in pre-release. Let me know if there's anything I can help you with!

**Comment by ad1Dima** [comment]
@ojhad sure. I gonna check this next week.
