### ISSUE TITLE
Feature: NumberBox (dev tracking)

### ISSUE THREAD

**Issue by teaP** [microsoft/microsoft-ui-xaml#1505]
Tracking for #483

- [x] Initial checkin after preliminary cleanup
- [x] Reimplement AcceptsCalculations et. al. Some notes for the current implementation:
    - [ ] Negative not supported in front of parens, e.g. "2 * -(3 + 2)"
    - [x] (3) doesn't evaluate to 3.
    - [x] -2 - 5 doesn't evaluate to -7.
    - [x] 5.09 + 14.333 = 19.423000000000002, why
    - [x] . needs to be globalized
    - [x] What is ComputePrecisionRounderSigDigits et. al. doing?
- [x] Additional features
    - [x] Add flyout spin buttons
    - [x] Treat NaN as an "unset" value, so the Text becomes an empty string.
- [ ] Bug fixes
    - [x] Doesn't evaluate when Text property changes
    - [x] Minimum can be larger than maximum, and vice versa
    - [x] Doesn't strip whitespace (so "5 " is invalid)
    - [x] When an invalid number is set as the value, we currently are sending ValueChanged twice.
    - [x] If a string/expression evaluates the current value, the string isn't replaced, but it should be.
    - [x] Could use a test for . vs ,
    - [x] Header should be an object; also add HeaderTemplate.
    - [x] When control gets focus it should select text. On evaluation, the caret should be moved to the end of the value.
    - [x] Spin buttons should gray out when min/max is hit (if validation is not disabled)
    - [x] What happens if you type in a number (or expression!) and hit the up/down buttons before it's evaluated...?
    - [x] Setting Text initially in markup doesn't do anything.
    - [x] Arrow keys only work on key up, so long press doesn't do anything (there's no repeat)
- [ ] Spec questions
    - [ ] How should the gamepad work -- should d-pad up/down increase/decrease the value?
    - [x] Shift-up/down does larger change? (Need additional property for this?)

**Comment by harvinders** [comment]
@teaP I am not sure if raising a issue is the best way to give feedback on something that is still under construction. I am using the latest preview and found following. 

* Setting `numberBox.Header = null` throws exception. Says, can't be set to null. However, for other controls like `ComboBox` , `TextBox` etc we are able to set it to `null`.  
* Also, could you please add support for `HeaderTemplate`, All other similar controls have it.

**Comment by teaP** [comment]
> @teaP Tammy Paine FTE I am not sure if raising a issue is the best way to give feedback on something that is still under construction. I am using the latest preview and found following.
> 
> * Setting `numberBox.Header = null` throws exception. Says, can't be set to null. However, for other controls like `ComboBox` , `TextBox` etc we are able to set it to `null`.
> * Also, could you please add support for `HeaderTemplate`, All other similar controls have it.

Thank you, @harvinders, for bringing this to my attention! Header was defined as a string for some reason, it's an object now like all the others. I've also added HeaderTemplate. The fixes will be in my next checkin, hopefully early next week.

**Comment by adrientetar** [comment]
Could ValueChanged only be sent when the user changed the value and not when programmatically setting it? Right now, I have to exclude that case manually cc @SavoySchuler

**Comment by teaP** [comment]
Hi @adrientetar, thanks for your feedback! In the prerelease control, the value should be committed on loss of focus -- is that not working for you? I also couldn't repro the disabled issue.

I've added the long press arrow key feature to my todo list. My next update will also treat NaN as an empty value. I'll start a discussion about Shift+up/down and get back to you on that one.

**Comment by adrientetar** [comment]
@teaP, actually yeah, the value is committed on loss of focus. My issue is that if I click on my app canvas it will deselect the items before the NumberBox has a chance to commit, because I guess focus lost event isn't sent out immediately but needs wait for the event loop to return.

[Video](https://www.youtube.com/watch?v=IuduYV9G2DI). The code change is [here](https://github.com/adrientetar/Fonte/commit/b004a3a74554102ce916e371b3f17ca7c849a611#diff-e7b7c7e44f272e446052fea25744bd55R304), also you can see I need a _isEditing boolean value to filter ValueChanged when it comes from the user, it would be nice if the control can do that internally maybe (or add a Reason property to the arguments perhaps to say if it's User change or Programmatic).

For the disabled issue, I use a converter on the value to set IsEnabled:

![image](https://user-images.githubusercontent.com/1250894/69209049-ad1a9380-0b0a-11ea-97d6-3706c342d464.png)

I also see some issues with decimal values that the decimal part gets dropped.

**Comment by teaP** [comment]
@adrientetar, hmm, would it help if you had a way to force validation of the text before you deselected the item in your canvas?

**Comment by adrientetar** [comment]
@teaP, not really because that would introduce too much coupling between parts of my app. I think I just need to do something like call CoreDispatcher.ProcessEvents so that the focus out event is processed immediately and before I deselect. So I don't think anything is required on the control, that's just something I thought I would note.

**Comment by adrientetar** [comment]
@teaP, it seems the NumberBox introduces 2 elements in the visual tree that receive focus

![image](https://user-images.githubusercontent.com/1250894/69745728-a639e500-10f7-11ea-9b21-38e4fbfcb9d0.png)

Here I see NumberBox get focus when tabbing and then InputBox as well. Shouldn't only NumberBox be in the tab focus order?

**Comment by jevansaks** [comment]
Thanks for letting us know @adrientetar, do you mind opening this as a new issue just so we don't lose it?

**Comment by jevansaks** [comment]
> * The SelectAll() when clicking into (focusing) NumberBox should happen on mouse up, not mouse down I think. If it happen on mouse down you can still potentially unselect part of the text before mouse up.

That is standard TextBox behavior and not something NumberBox is doing. I think it might be intentional. You might have seen it because you were trying the "hyper scrolling" feature which we ended up cutting from the 2.3 release.



> Here I see NumberBox get focus when tabbing and then InputBox as well. Shouldn't only NumberBox be in the tab focus order?

I tried this in the test app and I don't see this. Only one thing is getting visited by Tab when I tab through the page. Can you share a repro app?



> * When I click into the NumberBox and hit Up for the first time, it moves the cursor to the left instead of stepping up the value.

I see this, it's because TextBox eats that first Up to move the caret. We can try to get in the way and handle it, so go ahead and file an issue for this.

**Comment by mdtauk** [comment]
Assuming the default CornerRadius is set properly, here is the current styling in Light and Dark themes, as well as with different backgrounds

![image](https://user-images.githubusercontent.com/7389110/69765381-8b08bd00-116b-11ea-8d09-85c1b46ed451.png)


The compact flyout is visibly lost in the Dark Theme - using Acrylic for this flyout would be one way to solve it, as well as adding borders to these flyout buttons.

**Comment by teaP** [comment]
V1 finished, additional comments should go to #1736,
