### ISSUE TITLE
Pager Control checklist

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#2934]
### Prerelease readiness
- [ ] Dev: prototype + code review done
- [ ] Dev: quality review + code review done
- [ ] Dev: test coverage added
- [ ] Dev: initial accessibility review done
- [ ] Dev: telemetry implemented
- [ ] PM: spec up to date
- [ ] PM: feature ready for feedback
- [ ] PM: docs.microsoft.com updates ready
### Stable release readiness
- [ ] Dev: feature previously shipped in a prerelease NuGet package
- [ ] Dev: Azure CI tests passing
- [ ] Dev: accessibility review done
- [ ] Dev: API review done
- [ ] Dev: IDL attribute switched from preview to public
- [ ] Dev: Add test coverage to the NugetReleaseTest test
- [ ] PM: spec done
- [ ] PM: glob/loc, privacy, security, license compliance ready
- [ ] PM: customer validation done
- [ ] PM: docs.microsoft.com updated
- [ ] PM: Xaml Controls Gallery updated
