### ISSUE TITLE
Improvements for TabView Style Customizations [Issue Collection]

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#3737]
**Describe the bug**
The TabView style doesn't expose all values and is hard to customize in certain scenarios. There's a been a few specific bugs filed on these topics, but this issue is meant to encapsulate them as a larger set of targeted work to fix these issues together as a single update.

## Linked Issues

- [ ] TabView Padding isn't bound in Style as expected #3736
- [ ] TabViewItem should respect CornerRadius API #3084
- [ ] How do you increase the text size in the TabViewItems header? #3047
- [ ] TabViewItem should consume Foreground/Background properties #2653
- [ ] TabView should get a TabViewItemSeparatorForeground theme resource to style the tab separator #2742

**Comment by ranjeshj** [comment]
@stmoy as FYI

**Comment by duke7553** [comment]
I also think TabViewItems should support a null ThemeShadow value in case depth is not desired.

**Comment by mdtauk** [comment]
Ideally we should be able to set the Z Elevation in Xaml alone, so we could template and style the value, or even animate it.

**Comment by nahomebssa** [comment]
In case it hasn't been mentioned, TabView should have a customizable tab strip background.
